import { type NextRequest } from "next/server";
import { upsertBookDeleted } from "@/app/lib/models/Book";

// insert or update book deleted status.
// the request body contains an array of book information
// the book_id is generated by uuidv4
// the stock count and book information is not touched
// if the bookname is not found, a new book will be inserted, and with deleted status
// if the bookname is found, the deleted status will be updated
// return the updated or inserted books with recent deleted status
export async function POST(request: NextRequest) {
  const body = await request.json();
  if (!Array.isArray(body)) {
    return new Response("Body must be an array", { status: 400 });
  }

  const books = await upsertBookDeleted(body);
  if (!books || books.length === 0) {
    return new Response("Failed to update books deleted status", {
      status: 500,
    });
  }

  return new Response(JSON.stringify(books), { status: 200 });
}
